### ISSUE TITLE
"Data: textarea" and "State" wrappers perform poorly on iPad.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#432]
For https://github.com/phetsims/qa/issues/798. @arouinfar @kathy-phet FYI.

In https://github.com/phetsims/qa/issues/798#issuecomment-1104466769 @KatieWoe reported:
> Performance in the textarea and state wrappers on iPad were fairly poor.

"the textarea" is presumably the "Data: textarea" link in the Wrapper Index.

I'm surprised that these wrappers are being tested on iPad.  @samreid and @zepumph can you please comment? Are these wrappers intended to be tested on iPad?  Is their performance on iPad a concern?

**Comment by samreid** [comment]
It sounds OK for the text area and state wrappers to have poor performance on iPad.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar please decide if this issue is blocking for publication of GO 1.2.  Also please provide guidance on whether QA should be testing these wrappers on iPad.

**Comment by arouinfar** [comment]
@pixelzoom based on @samreid's comment, this is not a blocking issue. 

> Also please provide guidance on whether QA should be testing these wrappers on iPad.

Unless poor performance in a wrapper is indicative of poor performance of the student-facing simulation, I don't see any reason to test on iPad or Chromebook. However, this guidance should come from the PhET-iO team, so back to them.

**Comment by zepumph** [comment]
I agree, they should not be blocking. These wrappers test the top level of performance capabilities of PhET-iO, with printing tons to a text area and setting state many times back to back. In the vast majority of cases these are not what are exercised in student facing wrappers (though it is possible). These are cases where we leave it up to clients to test their wrappers on the devices their students will use. You can't expect an iPad to be able to set state on a complicated sim >1 time a second and still have good usability through that process.

**Comment by zepumph** [comment]
It should not. In https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#test-13-data-recording-wrapper-test I see that it says:

>Not supported on iPad or IE.

This is the same test, but it didn't get this documentation. @KatieWoe can you please add `Not supported on iPad` to test 12 also: https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#test-12-data-text-area-wrapper-test

**Comment by zepumph** [comment]
For the state wrapper, it is my recommendation to test on iPad. Here is what I would add as documentation for the test in the qa book:

>on iPad make sure the "set state rate" is only ever 0 or >3000, this will help prevent lag.

**Comment by KatieWoe** [comment]
Done in above commit

**Comment by KatieWoe** [comment]
As for https://github.com/phetsims/geometric-optics/issues/432#issuecomment-1110156317, this is different from what we were previously instructed to do. Text area was specifically supported on iPad since colorized and json were not. Is this something the whole team wants changed?

**Comment by samreid** [comment]
A spot check to make sure it runs on iPad sounds good, but text area wrapper performance does not need to be fast/smooth on iPad.

**Comment by pixelzoom** [comment]
This issue is still hanging around from a dev test that was done in April 2022.  And this sim is scheduled for QA and publication as part of https://github.com/orgs/phetsims/projects/44, which is likely to happen while I'm on vacation.  

@zepumph @samreid is there anything to do here, or should this issue be closed?

**Comment by zepumph** [comment]
Yes this issue can be closed in my opinion. We do not support the PhET-iO wrapper suite in iPad. There is though reason to think that the state wrapper should have some performance rigor attached to it, but it isn't clear how much. Perhaps we need a larger discussion to know what is acceptable for setting state. i.e. 1 per second on powerful machines, and 1 per 3 seconds for iPad.

**Comment by pixelzoom** [comment]
Closing based on @zepumph's opinion.
